./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Adipose - Subcutaneous-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Adipose - Subcutaneous-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Adipose - Visceral (Omentum)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Adipose - Visceral (Omentum)-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Adrenal Gland-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Adrenal Gland-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Artery - Aorta-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Artery - Aorta-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Artery - Coronary-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Artery - Coronary-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Artery - Tibial-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Artery - Tibial-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Bladder-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Bladder-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Amygdala-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Amygdala-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Anterior cingulate cortex (BA24)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Anterior cingulate cortex (BA24)-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Caudate (basal ganglia)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Caudate (basal ganglia)-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Cerebellar Hemisphere-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Cerebellar Hemisphere-enriched.txt" &
wait
echo "\n1/7 done\n"
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Cerebellum-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Cerebellum-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Cortex-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Cortex-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Frontal Cortex (BA9)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Frontal Cortex (BA9)-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Hippocampus-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Hippocampus-enriched.txt" &
wait
echo "\n2/7 done\n"
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Hypothalamus-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Hypothalamus-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Nucleus accumbens (basal ganglia)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Nucleus accumbens (basal ganglia)-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Putamen (basal ganglia)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Putamen (basal ganglia)-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Spinal cord (cervical c-1)-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Spinal cord (cervical c-1)-enriched.txt" &
wait
echo "\n3/7 done\n"
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Brain - Substantia nigra-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Brain - Substantia nigra-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Breast - Mammary Tissue-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Breast - Mammary Tissue-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Cells - EBV-transformed lymphocytes-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Cells - EBV-transformed lymphocytes-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Cells - Transformed fibroblasts-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Cells - Transformed fibroblasts-enriched.txt" &
wait
echo "\n4/7 done\n"
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Colon - Transverse-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Colon - Transverse-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Esophagus - Gastroesophageal Junction-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Esophagus - Gastroesophageal Junction-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Esophagus - Mucosa-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Esophagus - Mucosa-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Esophagus - Muscularis-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Esophagus - Muscularis-enriched.txt" &
wait
echo "\n5/7 done\n"
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Heart - Atrial Appendage-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Heart - Atrial Appendage-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Muscle - Skeletal-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Muscle - Skeletal-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Kidney - Cortex-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Kidney - Cortex-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Liver-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Liver-enriched.txt" &
wait
echo "\n6/7 done\n"
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Lung-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Lung-enriched.txt" &
./pathways.out "/Users/joaoalmeida/Desktop/Dissertacao/pathways/c2.cp.kegg.v5.2.symbols.gmt" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/protein/Minor Salivary Gland-overlay/part-00000" "/Users/joaoalmeida/Desktop/Dissertacao/sol/data/mitocondrias/feup-pp/project/data/output/correlations-output/Minor Salivary Gland-enriched.txt"
wait
echo "runAllEnrichment.sh done"
