#java -jar Dissert_old.jar "Adipose - Subcutaneous-overlay"
#java -jar Dissert_old.jar "Adipose - Visceral (Omentum)-overlay"
#java -jar Dissert_old.jar "Adrenal Gland-overlay"
#java -jar Dissert_old.jar "Artery - Aorta-overlay"
#java -jar Dissert_old.jar "Artery - Coronary-overlay"
#java -jar Dissert_old.jar "Artery - Tibial-overlay"
#java -jar Dissert_old.jar "Bladder-overlay"
#java -jar Dissert_old.jar "Brain - Amygdala-overlay"
#java -jar Dissert_old.jar "Brain - Anterior cingulate cortex (BA24)-overlay"
#java -jar Dissert_old.jar "Brain - Caudate (basal ganglia)-overlay"
#java -jar Dissert_old.jar "Brain - Cerebellar Hemisphere-overlay"
#java -jar Dissert_old.jar "Brain - Cerebellum-overlay"
#java -jar Dissert_old.jar "Brain - Cortex-overlay"
#java -jar Dissert_old.jar "Brain - Frontal Cortex (BA9)-overlay"
#java -jar Dissert_old.jar "Brain - Hippocampus-overlay"
#java -jar Dissert_old.jar "Brain - Hypothalamus-overlay"
#java -jar Dissert_old.jar "Brain - Nucleus accumbens (basal ganglia)-overlay"
#java -jar Dissert_old.jar "Brain - Putamen (basal ganglia)-overlay"
#java -jar Dissert_old.jar "Brain - Spinal cord (cervical c-1)-overlay"
#java -jar Dissert_old.jar "Brain - Substantia nigra-overlay"
#java -jar Dissert_old.jar "Breast - Mammary Tissue-overlay"
#java -jar Dissert_old.jar "Cells - EBV-transformed lymphocytes-overlay"
#java -jar Dissert_old.jar "Cells - Transformed fibroblasts-overlay"
#java -jar Dissert_old.jar "Colon - Transverse-overlay"
#java -jar Dissert_old.jar "Esophagus - Gastroesophageal Junction-overlay"
#java -jar Dissert_old.jar "Esophagus - Mucosa-overlay"
#java -jar Dissert_old.jar "Esophagus - Muscularis-overlay"
#java -jar Dissert_old.jar "Heart - Atrial Appendage-overlay"
#java -jar Dissert_old.jar "Kidney - Cortex-overlay"
#java -jar Dissert_old.jar "Liver-overlay"
#java -jar Dissert_old.jar "Lung-overlay"
#java -jar Dissert_old.jar "Minor Salivary Gland-overlay"
#java -jar Dissert_old.jar "Muscle - Skeletal-overlay"

echo "runAllfilter script done"
